### ISSUE TITLE
Prevent Form Submission or Integration With jQuery Validate

### ISSUE THREAD

**Issue by Joyrex** [ablanco/jquery.pwstrength.bootstrap#100]
Is there anything in the plugin to prevent form submission on an invalid or weak password, or better yet, integration with a library like jQuery Validate?

**Comment by ablanco** [comment]
https://github.com/ablanco/jquery.pwstrength.bootstrap/issues/79

Basically, add a function to the keyup event and there you can do whatever you need, you can even integrate it with jquery validate that wat.
