### ISSUE TITLE
Callback on rulesEngine.executeRules

### ISSUE THREAD

**Issue by dibiancoj** [ablanco/jquery.pwstrength.bootstrap#103]
Hi,

We had to make a change where if a specific rule is found then the end score would be **at least** "good". I wasn't able to override your executeRules methods because of the private closure. To accomplish this you can have a minimum level if a rule passes. So my new rule if passes, the min score would be 27. 
Or the more flexible way for the end developer would be the following:

      $('#test').pwstrength({
             .....
             TotalScoreCallbackAdjustment: function (totalTallyScore, word) {

            if (specificThingPassed) {

                //if we don't meet the requirement, then just return the lowest amount
                if (totalTallyScore <= 27) { <-- probably use the rule level from settings rather then hard coding
                    //just return the min amount
                    return 27;
                }
            }

            //otherwise just return whatever was tallied up
            return totalTallyScore;
        } 

Then in the plugin:

 rulesEngine.executeRules:

      rulesEngine.executeRules = function (options, word) {
            var totalScore = 0;

            $.each(options.rules.activated, function (rule, active) {
                if (active) {
                    var score = options.rules.scores[rule],
                        funct = rulesEngine.validation[rule],
                        result,
                        errorMessage;

                    if (!$.isFunction(funct)) {
                        funct = options.rules.extra[rule];
                    }

                    if ($.isFunction(funct)) {
                        result = funct(options, word, score);
                        if (result) {
                            totalScore += result;
                        }
                        if (result < 0 || (!$.isNumeric(result) && !result)) {
                            errorMessage = options.ui.spanError(options, rule);
                            if (errorMessage.length > 0) {
                                options.instances.errors.push(errorMessage);
                            }
                        }
                    }
                }
            });

            //give the calling code the ability to do whatever it wants with the score.
            if (options.TotalScoreCallbackAdjustment != null) {
                //give the callback a way to adjust the score
                totalScore = options.TotalScoreCallbackAdjustment(totalScore, word);
            }
            //end of new code **

            return totalScore;
        };

If you like the change let me know and I will put in a pull request.

**Comment by ablanco** [comment]
Hi Jason,
anything that makes the plugin more flexible and versatile is welcome. If you have a pull request there waiting to be sent, click that button!

I'm traveling in a couple days (vacations, yay!) so maybe I won't be able to merge the pull request until the end of the month.

Thanks for the contribution!
