### ISSUE TITLE
JSHint error

### ISSUE THREAD

**Issue by gruz** [ablanco/jquery.pwstrength.bootstrap#106]
When trying to JSHint my project including this plugin I get

```
   ../js/pwstrength-bootstrap.js
     61 |        var jQuery = require("jquery"),
                     ^ 'jQuery' is already defined.
```

What if to change this part from

https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/rules.js#L16

```javascript
        var jQuery = require("jquery"),
            jsdom = require("jsdom").jsdom;
```

to

```javascript
	   jQuery = require("jquery");
          var jsdom = require("jsdom").jsdom;
```

?

JQuery is really defined before this line as the main function parameter after you build 
https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/dist/pwstrength-bootstrap.js#L10

**Comment by ablanco** [comment]
Hi gruz,
the plugin is prepared for JSLint 2014 version, not JSHint. And also only to test for the files in src folder, no the bundled one.

The code that JSHint is complaining about is there only for the tests. It's not executed on the browser, so jQuery won't get redefined.

On the other hand it should be possible to remove the `var` as you propose. I'll try it and if it doesn't cause problems I'll change it.

**Comment by ablanco** [comment]
It's no good, the tests crash with that change: https://travis-ci.org/ablanco/jquery.pwstrength.bootstrap/builds/155297795
