### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by piernik** [ablanco/jquery.pwstrength.bootstrap#108]
Here is polish tanslation
```
{
    "wordLength": "Hasło jest zbyt krótkie",
    "wordNotEmail": "Hasło nie może być Twoim emailem",
    "wordSimilarToUsername": "Hasło nie może zawierać nazwy użytkownika",
    "wordTwoCharacterClasses": "Użyj innych klas znaków",
    "wordRepetitions": "Zbyt wiele powtórzeń",
    "wordSequences": "Hasło zawiera sekwencje",
    "errorList": "Błędy:",
    "veryWeak": "Bardzo słabe",
    "weak": "Słabe",
    "normal": "Normalne",
    "medium": "Średnie",
    "strong": "Silne",
    "veryStrong": "Bardzo silne"
}

```

BTW: hot to use it? I've added pl.json file and still in english

**Comment by ablanco** [comment]
Hi piernik, thanks a lot for the translation!

You can find how to use the translation [here](https://github.com/ablanco/jquery.pwstrength.bootstrap#internationalization-i18n). There is also an example -> [code](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/examples/bootstrap3/i18n.html) & [live](https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap3/i18n.html)

**Comment by piernik** [comment]
So it's not enough to include pl.json file?

**Comment by ablanco** [comment]
No, it's not enough. You can make use of a library like [i18next](http://i18next.com/) or write [your own](https://github.com/ablanco/jquery.pwstrength.bootstrap#how-to-customize-the-translation-function).

**Comment by piernik** [comment]
Oh that's pitty.
