### ISSUE TITLE
The plugin does not work on IE because of Math.log2

### ISSUE THREAD

**Issue by interDist** [ablanco/jquery.pwstrength.bootstrap#110]
No version of IE supports the log2 function in JS, crashing the plugin when trying to calculate the zxcvbn score, https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/2.0.3/src/methods.js#L40.

See http://kangax.github.io/compat-table/es6/#test-Math.log2 (under Built-in extensions > Math methods).
MDN suggests to use `Math.log(x) * Math.LOG2E` instead of `Math.log2(x)` in IE.

**Comment by ablanco** [comment]
Ok, I'll change it. Thanks!

**Comment by ablanco** [comment]
Fixed in 59e87ee784d8dd2de2389c0e02744faef18219d7
It will be available in the next release.
