### ISSUE TITLE
Bootstrap 4 alpha 6 support

### ISSUE THREAD

**Issue by tompazourek** [ablanco/jquery.pwstrength.bootstrap#114]
Alpha 6 of Bootstrap 4 changed how the progress bars work.

https://v4-alpha.getbootstrap.com/components/progress/

They don't use the <progress> element anymore, it's now rather similar to Bootstrap 3. And they also now use classes with `bg-` prefixes.

**Comment by ablanco** [comment]
Implemented in ed64f49cd2688f0cf593a6ce0385a99fe4db06d4

It will be available in the next release.

**Comment by tompazourek** [comment]
That was fast! Thanks a lot for your work :)
