### ISSUE TITLE
Progress extra CSS classes

### ISSUE THREAD

**Issue by Allerion** [ablanco/jquery.pwstrength.bootstrap#115]
It would be nice to be able to add extra CSS classes to the .progress element (Bootstrap 3&4) as well as the .progress-bar inside of it.

**Comment by Allerion** [comment]
Created a pr that does this.

**Comment by ablanco** [comment]
There is already an option to do this: `progressBarExtraCssClasses`

Here is an example: http://codepen.io/anon/pen/mWdbwK

**Comment by ablanco** [comment]
I just saw the pr. It adds the possibility to modify the bar container classes. Ok, I'll merge it now. Thanks for the contribution!

**Comment by Allerion** [comment]
Happy to contribute :)

**Comment by ablanco** [comment]
I'll try to make a new release later today with this change.
