### ISSUE TITLE
status Classes can be wrong 

### ISSUE THREAD

**Issue by ptitgraig** [ablanco/jquery.pwstrength.bootstrap#117]
Hello
I've notice a UI bug. When using statusClasses, the `ui.updateFieldStatus() cssClass`  parameter can take values 4 and 5. These are used later to guess the css class to apply on the field.
But the `statusClasses` has only 3 entries. So `4` and `5` index will return undefined.
You can fixe it with the following code:
```javascript
cssClass = statusClasses[Math.floor(cssClass/2)];
```
Thanks for considering the fix.

**Comment by ablanco** [comment]
Thanks for reporting this, I'll try to fix it this weekend.

**Comment by ablanco** [comment]
Fixed in 283d3b7059a4307426ab74425b6d502d91523de8
