### ISSUE TITLE
Popovers On responsive

### ISSUE THREAD

**Issue by copremesis** [ablanco/jquery.pwstrength.bootstrap#121]
If the page is resized then the popover is frozen in place ...

**Comment by copremesis** [comment]
Switching from absolute to relative fixes this 

```  $('#password').next('div[id*="popover"]').css({position: 'relative', top: 'auto', left: '271'})```

**Comment by ablanco** [comment]
This looks like an issue for the Bootstrap guys.

https://github.com/twbs/bootstrap
