### ISSUE TITLE
Error: Method ruleIsMet does not exist on jQuery.pwstrength-bootstrap

### ISSUE THREAD

**Issue by Quix0r** [ablanco/jquery.pwstrength.bootstrap#125]
This happens with the minimized `master` version, but not the unminimized (_and customized?_). Sadly, one of my collegs has taken `master` (2.0.8) not the latest release 2.0.6 where he added that said method.

Here it is:
````
		onScore: function (options, word, score) {
			showValidationResult('rule8CharsMinimum', $(passFields).pwstrength('ruleIsMet', 'wordLengthStaticScore'));
			showValidationResult('ruleOneLowerCase', $(passFields).pwstrength('ruleIsMet', 'wordLowercase'));
			showValidationResult('ruleOneUpperCase', $(passFields).pwstrength('ruleIsMet', 'wordUppercase'));
			showValidationResult('ruleOneNumber', $(passFields).pwstrength('ruleIsMet', 'wordOneNumber'));
			showValidationResult('ruleOneSpecialChar', $(passFields).pwstrength('ruleIsMet', 'wordOneSpecialChar'));
		}
````
Better is, should I go ahead and fork + add a PR? It is "open-sourced" on the public website anyway.

**Comment by Quix0r** [comment]
It seems I use a customized build. Even when I use `master`, the said method is not there.

**Comment by Quix0r** [comment]
So maybe mark this _invalid_ after all.

**Comment by ablanco** [comment]
Hi Roland,
the method `ruleIsMet` is not part of the library, it's probably a custom one.

The library is 100% open source, the minimized version is the same one as the unminimized one. You are welcome to collaborate in any way, all contributions are useful.

**Comment by Quix0r** [comment]
Here it is:
````
	methods.ruleIsMet = function (rule) {

		if ($.isFunction(rulesEngine.validation[rule])) {

			if (rule == 'wordLength') {
				rule = 'wordLengthStaticScore';
			}

			var rulesMetCnt = 0;

			this.each(function (idx, el) {
				var options = $(el).data("pwstrength-bootstrap");

				rulesMetCnt += rulesEngine.validation[rule](options, $(el).val(), 1);
			});

			return rulesMetCnt == this.length;
		} else {
			$.error("Rule " + rule + " does not exist on jQuery.pwstrength-bootstrap.validation");
		}
	}
````
`wordLength` seems to be mapped to `wordLengthStaticScore`. If that is okay, I commit and create a PR.

**Comment by Quix0r** [comment]
Should I better remove any mods from it and convert it into a custom rule check?

**Comment by ablanco** [comment]
You can commit and send a pull request. It counts the number of inputs that pass the rule, right? It would be great if you could also add the method to the documentation in the PR.

Thanks!
