### ISSUE TITLE
Rules only

### ISSUE THREAD

**Issue by bigalnz** [ablanco/jquery.pwstrength.bootstrap#130]
I would like to know if there is anyway to get pwstrength to prevent submit until it meets rules (as opposed to doing it based on score.

Similar to this : https://github.com/ablanco/jquery.pwstrength.bootstrap/issues/79 

but based purely on rules:
Min 8 
Upper 1
Special 1
Numerical 1

Thanks

**Comment by ablanco** [comment]
Hi Al, you can make use of the new method `ruleIsMet`. That allows you to check if the password passes an specific rule.

So build a function that fires when the user types and checks if the rules you are interested in are met through that method.
