### ISSUE TITLE
Very Weak text displaying only "Very" when showVerdictsInsideProgressBar is true

### ISSUE THREAD

**Issue by BriceRoncace** [ablanco/jquery.pwstrength.bootstrap#132]
Quick fix was to change the `"Very Weak"` value to `"Very&nbsp;Weak"`

**Comment by Synchro** [comment]
I found that I needed to change `ui.progressBarMinPercentage` to 21 to fit it in the progress bar.

**Comment by ablanco** [comment]
I think this should be fixed with styles, not code. Adding `white-space: nowrap;` to the styles of the `.password-verdict` object fixes it.

I did that in 4fea9f64ea219047de5bbd9bb77d0c835ef43504
