### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by bigalnz** [ablanco/jquery.pwstrength.bootstrap#133]
Hello,

I am just looking at how to add error messages for rules like Upper, Digit, Special etc.

I am using rules is met to enforce use of these rules.

From reading the docs it looks like I need to copy from the src/locales folder the en.json file and then for example add:

"wordOneSpeicalChar" : "You need a special Character"

Then I need to add a copy of en.json into my js folder in my project?

Then I need to set option.i18n = {} <<-- but not sure what to put in the braces?

Can someone please advise?

Thanks

Al

**Comment by ablanco** [comment]
By default it tries to make use of this library: https://www.i18next.com/
You can find an example of this here: https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap3/i18n.html

If you don't want to use it, then you can make you own translation function. It is explained here: https://github.com/ablanco/jquery.pwstrength.bootstrap#how-to-customize-the-translation-function
You need to pass an object with a `t` method to the `i18n` option. That `t` method is the function that will translate the text. That function code is up to you, as it's how to pass the content from the json file to it.
