### ISSUE TITLE
How to retrieve current score?

### ISSUE THREAD

**Issue by Synchro** [ablanco/jquery.pwstrength.bootstrap#137]
I'm looking for a function that will allow me to fetch the current score from pwstrength. This is so I can use jquery.validate to query the score and use that in a validation rule. I was hoping for something like `$('#password').pwstrength.score`, but I can't find anything like that. Next stop was try get it to update a global variable using onScore, however as #136 says, I can't make that work either. I tried sending it a `change` event, and that triggers, but it doesn't return the score. How should I do this?

**Comment by ablanco** [comment]
Hi Marcus. There is no method per se to get the score, but you can make use of the `onKeyUp` event. There is an example in #45

**Comment by ablanco** [comment]
I've just checked and that example is broken. I've fixed the broken link [here](http://jsfiddle.net/v98j4tox/2/)
