### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by sahilchopra** [ablanco/jquery.pwstrength.bootstrap#139]
npm install --save pwstrength-bootstrap

import popper from 'popper.js/dist/popper';
import bootstrap from 'bootstrap/dist/js/bootstrap';
import pwStrength from 'pwstrength-bootstrap/dist/pwstrength-bootstrap';

After importing pwStrength I am getting following error

Critical dependency: the request of a dependency is an expression

Please guide me if i m missing any thing

**Comment by sahilchopra** [comment]
Logs

ERROR in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Error: Can't resolve 'child_process' in '/home/sahil/app/app/BiscuitWeb/node_modules/jsdom/lib/jsdom/living'
 @ ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js 4:18-42
 @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
 @ ./node_modules/jsdom/lib/jsdom.js
 @ ./node_modules/pwstrength-bootstrap/dist/pwstrength-bootstrap.js
 @ ./src/components/password_meter.js
 @ ./src/containers/auth/setnew_password.js
 @ ./src/containers/auth/send_instruction.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js

ERROR in ./node_modules/cssstyle/lib/CSSStyleDeclaration.js
Module not found: Error: Can't resolve 'fs' in '/home/sahil/app/app/BiscuitWeb/node_modules/cssstyle/lib'
 @ ./node_modules/cssstyle/lib/CSSStyleDeclaration.js 7:9-22
 @ ./node_modules/jsdom/lib/jsdom/level2/style.js
 @ ./node_modules/jsdom/lib/jsdom/living/index.js
 @ ./node_modules/jsdom/lib/jsdom.js
 @ ./node_modules/pwstrength-bootstrap/dist/pwstrength-bootstrap.js
 @ ./src/components/password_meter.js
 @ ./src/containers/auth/setnew_password.js
 @ ./src/containers/auth/send_instruction.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js

ERROR in ./node_modules/jsdom/lib/jsdom.js
Module not found: Error: Can't resolve 'fs' in '/home/sahil/app/app/BiscuitWeb/node_modules/jsdom/lib'
 @ ./node_modules/jsdom/lib/jsdom.js 6:11-24
 @ ./node_modules/pwstrength-bootstrap/dist/pwstrength-bootstrap.js
 @ ./src/components/password_meter.js
 @ ./src/containers/auth/setnew_password.js
 @ ./src/containers/auth/send_instruction.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js

**Comment by ablanco** [comment]
Hi, it seems like you're loading the plugin as a module, but that is not supported. It doesn't support any kind of module declaration, not CommonJS, AMD, nor ES6.

I'm currently not implementing new features in the plugin, I only do maintenance work. But if you are interested in implementing module capabilities I would be more than happy to merge it and release it. All contributions are welcome.
