### ISSUE TITLE
Not all activated rules fire an error

### ISSUE THREAD

**Issue by patlecat** [ablanco/jquery.pwstrength.bootstrap#140]
I would like to use **wordUpperLowerCombo** and **wordLetterNumberCombo** and **wordNotEmail** but none of them ever displays as error in the pop-over :( Why not? What do I have to do?

It works fine for checking the username, repeated letters and sequences and length of course.

I use Bootstrap3 example as the basis and jQuery 2.2.4

**Comment by ablanco** [comment]
Hi, you need to define the error message for those rules. Only a few have a default message.

You need to add the message to the translation dictionary you're using, and you must put the rule name as the key. Check out the example translation files in [here](https://github.com/ablanco/jquery.pwstrength.bootstrap/tree/master/locales).

You'll also have to read how to use the translations, the documentation is [here](https://github.com/ablanco/jquery.pwstrength.bootstrap#internationalization-i18n).
