### ISSUE TITLE
Password "111111" has a score of 21 under default settings

### ISSUE THREAD

**Issue by johnnyshields** [ablanco/jquery.pwstrength.bootstrap#144]
This is a "normal" range score. I would expect it to be much lower.

**Comment by ablanco** [comment]
Yes, you're right. It would make sense for it to be lower. Maybe we should increase the repetition penalty cost, or the lack of letters and symbols.

**Comment by johnnyshields** [comment]
I think repetition penalty cost should be increased.

**Comment by ablanco** [comment]
The rule wasn't activated by default. Fixed here: 1293ebdffd4863a4059d9f17c5081658961d905a
