### ISSUE TITLE
Password "password" has a strength of 20

### ISSUE THREAD

**Issue by johnnyshields** [ablanco/jquery.pwstrength.bootstrap#145]
Seems higher than it should be

**Comment by ablanco** [comment]
Hi Johnny, you can change the weights in the [rules options](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md#rules) and adapt it to your needs.

**Comment by johnnyshields** [comment]
@ablanco I'm aware but this should be handled out-of-the-box... "password" is by any measure a weak password, and It's coming up as "Normal"

**Comment by ablanco** [comment]
Yeah, that makes sense. I guess I could add a new rule that checks for the most common passwords, do you happen to have a list of the most common passwords?

**Comment by johnnyshields** [comment]
According to this article most of the common passwords tend to be single words or number strings. Firstly I think we should increase the penalty for using only one character type in the password.

The only weak passwords that aren't caught by this are ones that are:
- keyboard sequences such as 1qaz2wsx3edc or 1q2w3e4r5t.
- character substitutions like p4ssw0rd or pa$$word
- prefixing/suffixing like $password1

Here's a list of the most common passwords:
http://www.passwordrandom.com/most-popular-passwords

**Comment by ablanco** [comment]
Implemented in 38cf6148b850eef1ba2e714251c1822592cd3772

**Comment by johnnyshields** [comment]
@ablanco awesome, thanks!!
