### ISSUE TITLE
Popover: Cannot set property 'content' of undefined

### ISSUE THREAD

**Issue by tim-tx** [ablanco/jquery.pwstrength.bootstrap#149]
Chromium reported an error with the following line, and no popover was displayed: 
https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/d85d216836b5556c33be317d4bf88fab8d29e0b5/src/ui.js#L233
I saw in the debugger `popover` did not have `options`, but it did have `config.content`. Changing the line above to `popover.config.content = html;` gave me the expected behavior.

**Comment by ablanco** [comment]
What version of Bootstrap are you using?

**Comment by tim-tx** [comment]
Bootstrap 4.0.0. I see now there is a `bootstrap4` option (setting to `true` did not help), as well as a warning that Bootstrap 4 support is very basic.

**Comment by ablanco** [comment]
Yes, BS4 support is quite limited. I have to work on that and make it the default option, now that BS4 is out of beta.

**Comment by ablanco** [comment]
@tim-tx I've started working on BS4 support by default here: https://github.com/ablanco/jquery.pwstrength.bootstrap/tree/bs4

The popover works in that branch. To use it, you'll have to compile the plugin.

**Comment by ablanco** [comment]
Fixed in https://github.com/ablanco/jquery.pwstrength.bootstrap/releases/tag/3.0.0
