### ISSUE TITLE
Password with consecutive same chars VERY STRONG ??

### ISSUE THREAD

**Issue by itajackass** [ablanco/jquery.pwstrength.bootstrap#150]
For example: qqqqqqqqqqqqqqqqqqqqqqqq

Why indicate VERY STRONG????

This is my config:

        var pswoptions = {};

	pswoptions.common = {
		usernameField: "#nomeUtente"
	};

	pswoptions.rules = {
		activated: {
			wordTwoCharacterClasses: true,
			wordRepetitions: true
		}
	};

	pswoptions.ui = {
		showVerdictsInsideProgressBar: true
	};

	$('#password').pwstrength(pswoptions);

**Comment by ablanco** [comment]
That's because length eventually wins over repetition. If you want, you can give more penalizing score to the repetition rule.

You have [an example here](https://codepen.io/anon/pen/YLrZzg?editors=1011#0), with a penalization of `-100`.
