### ISSUE TITLE
closest container

### ISSUE THREAD

**Issue by Erwane** [ablanco/jquery.pwstrength.bootstrap#152]
Hi and thanks for work.

Like #7 i need to put the progress in the closest class container.

Instead of limit the container to "#field-id" could you use ".closest(options.ui.container)" ?

this allow multiple strenght password in same page

Thanks

**Comment by ablanco** [comment]
Hi Erwane, sorry for the late answer, been busy lately.

Do you mean [here](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/ui.js#L25)? 

I don't understand the issue, can you elaborate? It's already possible to have [several strength meters in one page](https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap2/multi.html).
