### ISSUE TITLE
container for Verdicts [feature suggestion]

### ISSUE THREAD

**Issue by nullmem** [ablanco/jquery.pwstrength.bootstrap#153]
A really useful UI option would be the ability to specify a container for verdicts.

**Comment by ablanco** [comment]
I was gonna implement this but I've realized it's already in the plugin XD

It's in the `viewports` option in [ui options section](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md#user-interface).

Here is an example of this in action: https://codepen.io/anon/pen/XPKQVq?editors=1010
