### ISSUE TITLE
progress bar color doesn't change in bootstrap3 - option not being checked properly

### ISSUE THREAD

**Issue by jasoncable** [ablanco/jquery.pwstrength.bootstrap#154]
https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/86a5383e7293c0a28a31a358ecaed323cbb131b3/src/ui.js#L157

Missing ui object on bootstrap3 check.  Should be:
`if (options.ui.bootstrap2 || options.ui.bootstrap3) {`

**Comment by kkalbaugh** [comment]
Having the same issue

**Comment by ablanco** [comment]
Fixed in v3.0.1. Thanks for reporting it!
