### ISSUE TITLE
ruleIsMet does not work with custom rules

### ISSUE THREAD

**Issue by hsuanhan** [ablanco/jquery.pwstrength.bootstrap#159]
After adding a custom rule, I tried to use ruleIsMet method to check to see if my custom rule is met. However it always throws this error in the console: Uncaught Error: Rule wordFourCharacterClasses does not exist on jQuery.pwstrength-bootstrap.validation. Can this be fixed to work with custom rules?

`var options = {};
    options.common = {
      minChar: 10
    };
    options.rules = {
      activated: {
        wordTwoCharacterClasses: true,
        wordRepetitions: true
      }
    };
    options.ui = {
      container: "#pwd-container",
      showPopover: true,
      showErrors: true,
      showVerdictsInsideProgressBar: true,
      viewports: {
        progress: ".pwd_progress"
      }
    };
    $("#dbpassword").pwstrength(options);
    $("#dbpassword").pwstrength(
      "addRule",
      "wordFourCharacterClasses",
      function(options, word, score) {
        if (
          word.match(/([a-z].*[A-Z])|([A-Z].*[a-z])/) &&
          word.match(/([0-9])/) &&
          word.match(/(.[!,@,#,$,%,\^,&,*,?,_,~])/)
        ) {
          return score;
        }
        return;
      },
      10,
      true
    );
    $("#dbpassword").pwstrength('ruleIsMet', 'wordFourCharacterClasses'); <-- this fails
  }
);
`

**Comment by ablanco** [comment]
I've put this on an codepen: https://codepen.io/anon/pen/vPjLVp?editors=1011

And yes, it fails, I'll fix it.

**Comment by ablanco** [comment]
Fixed in 0020585c0770669f8106199059d6511a9032550d

It will be released in 3.0.4 version.
