### ISSUE TITLE
Special Char Validation doesn't recognize certain special characters

### ISSUE THREAD

**Issue by hsuanhan** [ablanco/jquery.pwstrength.bootstrap#161]
Current validation for special characters is this:
word.match(/[!,@,#,$,%,\^,&,*,?,_,~]/)

This doesn't recognize slashes ("/", "\") as special characters.

Can it allow all special characters besides the ones excluded in **invalidCharsRegExp** option?

**Comment by ablanco** [comment]
What do you suggest? 

Adding symbols to [this line](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/rules.js#L82)? Or putting the list of symbols in an option?

**Comment by hsuanhan** [comment]
I think having the option to override existing symbols would be a better long term solution.
