### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by JD-aus** [ablanco/jquery.pwstrength.bootstrap#163]
[This package](https://www.jsdelivr.com/package/npm/pwstrength-bootstrap) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by ablanco** [comment]
Done in b25c60d0291e8abd1b115026a2957eefb9abe982
