### ISSUE TITLE
Prevent submission if password is weak

### ISSUE THREAD

**Issue by thewebartisan7** [ablanco/jquery.pwstrength.bootstrap#165]
I am using jsvalidate plugin and I would like to prevent form submission if password is weak.
Add the moment I can add custom rule in jsvalidate, but this of pwstrength are different for example if using zxcvbn library.
I can see various method, for example onScore() could be right place to prevent form submission?
Or there is another way?

**Comment by thewebartisan7** [comment]
I suppose that... Would be good to prevent form submission if score is weak, otherwise I have to store score onScore event and then check on submitHandler of jsvalidation. Not a big problem, I can manage it.

**Comment by ablanco** [comment]
I'm afraid the library only generates and displays the strength meter, it doesn't cover validation. You'll have to store the score from the `onScore` event.

**Comment by thewebartisan7** [comment]
Ok thanks!
