### ISSUE TITLE
Long character will result in Very Strong verdict

### ISSUE THREAD

**Issue by HadiAkmal** [ablanco/jquery.pwstrength.bootstrap#167]
This is my config: 

```
        options.rules = {
          activated: {
            wordNotEmail: true,
            wordLength: true,
            wordSimilarToUsername: true,
            wordSequences: false,
            wordRepetitions: false,
            wordLetterNumberCharCombo: true
          },
          scores: {
            wordRepetitions: -100
          }
        };
```

My requirement is to allowed minimum of 8 character password with Letter, Number and Char combo such as this: **qqqqqq@1**

But when I type **ssssssssssssssssss** the verdict is **Very Strong**. How do I solve this problem? Thanks in advance.

**Comment by HadiAkmal** [comment]
I'm not sure whether this is the correct way to do it but this code fulfill my requirement.

```
            onScore: function (options, word, totalScoreCalculated) {
              if (word.length >= 8 && $("#inputPassword").pwstrength("ruleIsMet", "wordLetterNumberCombo") === true && $("#inputPassword").pwstrength("ruleIsMet", "wordOneSpecialChar") === true) {
                return totalScoreCalculated
              } else if ((word.length >= 8 || word.length < 8) && $("#inputPassword").pwstrength("ruleIsMet", "wordLetterNumberCombo") === true) {
                return options.ui.scores[1]
              } else if ((word.length >= 8 || word.length < 8) && $("#inputPassword").pwstrength("ruleIsMet", "wordOneSpecialChar") === true) {
                return options.ui.scores[1]
              }
            }
```

Also I need to check `ruleIsMet` with both `wordLetterNumberCombo` and `wordOneSpecialChar` because `wordLetterNumberCharCombo` will return `true` even there's no number when I keyin password.

![image](https://user-images.githubusercontent.com/14165645/103149828-4c976480-47a8-11eb-9422-6033044fc2a1.png)

**Comment by ablanco** [comment]
Hi. There are several ways you can achieve it.

Maybe the cleanest way would be to add a custom rule where you enforce your requirements: https://github.com/ablanco/jquery.pwstrength.bootstrap#adding-custom-rules

You can made your checks there, and return a big negative score if the password does't match them.
