### ISSUE TITLE
Progress div is created multiple times

### ISSUE THREAD

**Issue by cryo75** [ablanco/jquery.pwstrength.bootstrap#169]
I implemented the code as per the examples for Bootstrap 4.

```html
    <div id="password-container">
        <div class="form-group mb-3">
            <div class="input-group">
                <input asp-for="Password" class="form-control" id="password" />
                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-lock"></span>
                    </div>
                </div>
            </div>
            <div style="padding-top: 2px;">
		        <div class="password-progress" style="height: 2px;"></div>
            </div>
            <small>
                <span asp-validation-for="Password" class="text-danger"></span>
            </small>
        </div>
    </div>
```

The progress div is created 2 or 3 times:

![image](https://user-images.githubusercontent.com/3060986/115152713-784d9b80-a072-11eb-8255-dc02fca7c470.png)

**Comment by cryo75** [comment]
The problem is because in some forms I might have multiple password inputs (eg. Old Password, New Password, Confirm Password). How can I link the indicator with just one on them?

**Comment by ablanco** [comment]
When you initialize the meter with a code similar to this `$(':password').pwstrength();` the meter will be generated for all the inputs that the query matches.

Here the selector `$(':password')` matches all password inputs in the document, if you only want to attach it to some, you can use classes or ids in the selector. The meter will be only attached to those that match the selector.
