### ISSUE TITLE
username common usernameField

### ISSUE THREAD

**Issue by janessaallen** [ablanco/jquery.pwstrength.bootstrap#50]
Hi, in the options.js file, I'm trying to change the default option name for the usernameField from "#username" to "#UserName" and it does not seem to be recognizing my input field with that name (to issue an error message). Do you know why that would be? Is there another place where I need to change the field name?

**Comment by ablanco** [comment]
There is no other place where that identifier is written. `options.js` is the file to modify.

Are you using a built made with your modified version of `options.js`. The only thing I can think of is that your are using a final file compiled with the original `options.js`.

**Comment by janessaallen** [comment]
From the download, I’m using the js from the examples folder.  Are those correct?

 

examples/pwstrength.js

examples/bootstrap3/bootstrap3.js

**Comment by ablanco** [comment]
That file `pwstrength.js` in examples is the result of building the whole thing. If you modify the `options.js` file, you have to rebuild the plugin. For that I use `grunt`. You have more details on how to build the bundle at the end of the readme.

**Comment by janessaallen** [comment]
thanks
