### ISSUE TITLE
Negative values show no bar

### ISSUE THREAD

**Issue by princeofnaxos** [ablanco/jquery.pwstrength.bootstrap#52]
The growing bar to show the password strength is nice, but when negative values are possible, then there will be no bar at all. This means, that I could type a very weak password, but get no verdict.

It would be better to produce "width: 1%" when the result is negative instead of 0%.

**Comment by ablanco** [comment]
I have implemented this in 23104bf02adb6276e91b98c790d0de92e4074612

It will be available in the next release.
