### ISSUE TITLE
Hide the verdict if the password field is empty

### ISSUE THREAD

**Issue by princeofnaxos** [ablanco/jquery.pwstrength.bootstrap#53]
If typing a password and then removing it again, the bar is gone but the verdict is still there.

Should add:

	$(this).on('keyup', function () {
		$(this).find('+ .progress').show().find('+ .password-verdict').show()
		if ($(this).val().length == 0) $(this).find('+ .progress').hide().find('+ .password-verdict').hide()
	})

or similar,

and on init hide .progress and .password-verdict.

**Comment by ablanco** [comment]
Implemented in 5a582c3727419f4d5e175e3793abdea49c9a7d32

It will be available in the next release.
