### ISSUE TITLE
custom  rules

### ISSUE THREAD

**Issue by cleder** [ablanco/jquery.pwstrength.bootstrap#54]
I'd like to have a rule that only accepts passwords that have
* at least one Uppercase char
* at least one lowercase char
* at least one number
* minimum 6 chars

I am sure this is quite possible with the library, but the documentation is lacking a bit here. How do I achieve this?

**Comment by ablanco** [comment]
Yes, it is possible. You need to add a custom rule, you can find the doc [here](https://github.com/ablanco/jquery.pwstrength.bootstrap#adding-custom-rules). There is also an [example](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/examples/bootstrap2/rules.html).

The idea is to call the method `addRule` and pass it a function and a score. The function will receive the score associated to the rule as a parameter, and must return `false` or a numeric value (usually the very same score). The function can calculate the return value in anyway it wants, but the idea is that if the function criteria matches with the password then it should return the score (a negative one if it's a penalization). The returned value by the function will be added to the password total score.

You can find plenty of examples of these functions in the [rules.js file](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/rules.js).

**Comment by cleder** [comment]
turns out what I really *WANTED* was:

        jQuery(document).ready(function () {
            "use strict";
            var options = {};
            options.ui = {
                showPopover: true,
                showErrors: true,
                errorMessages : {
                    wordUpperLowerCombo: "Must contain UPPER- and lowercase letters",
                    wordLetterNumberCombo: "Must contain numbers and Letters",
                }
            };
            options.rules = {
                activated: {
                    wordNotEmail: true,
                    wordRepetitions: true,
                    wordUpperLowerCombo: true,
                    wordLetterNumberCombo: true
                },
            };
            $('#password').pwstrength(options);
        });

So I had to add `errorMessages` for `wordUpperLowerCombo` and `wordLetterNumberCombo` and display them in a popover to guide the user to fulfill all three (+minLenght=6) requirements

**Comment by ablanco** [comment]
I'm glad you found a way to make it work as you wanted :)
