### ISSUE TITLE
Bug with zxcvbn

### ISSUE THREAD

**Issue by GreyHead** [ablanco/jquery.pwstrength.bootstrap#57]
If you use the zxcvbn option there is a bug with the userInputs array; if it includes undefined values then zxcvbn throws an error.

This will happen if the `usernameField` option is not set. 

Also the current setup does not support a fixed word list being passed to zxcvbn:
> "This list is also good for site-specific vocabulary. For example, ours includes dropbox."

I have added an additional option to allow a word list:

    defaultOptions.common.zxcvbnWords = [];

and validation to the push() lines in the zxcvbn call:
```javascript
            if (options.common.zxcvbn) {
                userInputs = options.common.zxcvbnWords;
                $.each(options.common.userInputs, function (idx, selector) {
                    if ($(selector).val()) {
                        userInputs.push($(selector).val());
                    }
                });
                if ($(options.common.usernameField).val()) {
                    userInputs.push($(options.common.usernameField).val());
                }
                score = zxcvbn(word, userInputs).entropy;
            } else {
                score = rulesEngine.executeRules(options, word);
            }

**Comment by ablanco** [comment]
Done in 56fb470c6b2a9869172a5308d8f97bc2b7232b4c

**Comment by GreyHead** [comment]
Thank you
