### ISSUE TITLE
Adding "012" to any password makes it weaker

### ISSUE THREAD

**Issue by seriousmumbo** [ablanco/jquery.pwstrength.bootstrap#59]
The password strength drops whenever I add "012" to the end of a password.

Examples:

Simple password:
"goop33" = medium
"goop33012" = nill 

Random 12 character:
"Fa2PmxBTTWzT" = strong
"Fa2PmxBTTWzT012" = normal
"012Fa2PmxBTTWzT" = weak 
"Fa2012PmxBTTWzT" = normal
"Fa2PmxBTTWzTpassword" = very strong

Random 20 character:
"Nq4YGDQf3HJcXU3ZDsjv" = very strong
"012Nq4YGDQf3HJcXU3ZDsjv" = strong
"Nq4YGDQf3HJcXU3ZDsjv012" = very strong <-- doesn't drop if I add "012" anywhere past 7 chars
"Nq4Y012GDQf3HJcXU3ZDsjv" = strong

**Comment by ablanco** [comment]
012 makes the score to drop because it is a sequence, but it seems like the `wordSequences` needs some polishing so the scores are more consistent.

You can change the score associated to finding sequences, or even deactivate the rule if you don't like it.

**Comment by melanie** [comment]
+1 - the sequence rules seem exceptionally aggressive; even flopping my hands willy-nilly on the keyboard for 30 characters produced "sequences" that make the password Weak, despite the practical impossibility of breaking such a password.

**Comment by ablanco** [comment]
I've changed the default score of the sequences rules, so it is not that aggresive.

Commit: 9d7aa00f6e4b846ccc2325d6d8d2b591b48c1bd5
