### ISSUE TITLE
Errors not showing with zxcvbn  

### ISSUE THREAD

**Issue by Cr1T1cal** [ablanco/jquery.pwstrength.bootstrap#64]
Hi i've noticed my errors are not longer showing when i added the zxcvbn:true 
my errors where showing untill i added zxcvbn, i was just wondering if there is a way to get error messages to still show with zxcvbn

heres the part of code;

        var input = $("#register_password");
            input.pwstrength({
                common: {
                	 onLoad: function() {
					      $('#messages').text('Start typing password');
					    },
					 minChar: 8,
					 zxcvbn: true,
					 usernameField: "#username",
					 userInputs: ['#firstname', '#lastname', '#displayname', '#email'],
					 debug: true
				},
				rules: {
					raisePower: 1.4,
					activated: {
				        wordTwoCharacterClasses: true,
				        wordRepetitions: true
				    }
				},
				ui: { 
					container: ".password-strength",
					showErrors: true,
					showStatus: true,
					showVerdictsInsideProgressBar: true,
					verdicts: ["Weak", "Normal", "Medium", "Strong", "Very Strong"],
					viewports: {
					  progress: ".password-progress",
					  errors: ".password-errors"
    				   }
			        },
                });
                input.pwstrength("addRule", "demoRule", function (options, word, score) {
                    return word.match(/[a-z].[0-9]/) && score;
                }, 10, true);

**Comment by ablanco** [comment]
Hi Cr1T1cal,
I'm afraid is not possible to show the errors when the zxcvbn is activated. The errors are generated by the internal evaluation engine, when the zxcvbn engine is activated the internal one is not longer used. And zxcvbn only returns the password entropy, it doesn't return a list of motives explaining why that is the entropy of the password.
