### ISSUE TITLE
Minify fails to compress source

### ISSUE THREAD

**Issue by erikpoehler** [ablanco/jquery.pwstrength.bootstrap#65]
I have the latest minify version and the latest version of jquery.pwstrength.bootstrap but when adding this plugin to my list of scripts, minification fails.
Am I doing something wrong?

**Comment by ablanco** [comment]
Hi, are you using the minified version? If you are adding it to a list of files that are going to be minified then you should probably use the non minified version of the file.

**Comment by erikpoehler** [comment]
Nope. The regular dev version. uncompressed. Have you tested compression with different tools? YUI? Google Closure? So I know what tool to switch to...

**Comment by ablanco** [comment]
I'm using uglify, it's the only one I've tested.
