### ISSUE TITLE
To show Password Strength Progress Bar inside Popover

### ISSUE THREAD

**Issue by arunkarty** [ablanco/jquery.pwstrength.bootstrap#66]
Hi,

Pl. help me to show Password Strength Progress Bar inside Popover. While start typing password inside a textbox, need to show popover with Progres bar and Error messages inside.

Pl. let me know is this possible?

**Comment by ablanco** [comment]
Hi. You can make use of the `container` and `viewports` options. If you define a container that will contain both the password input and the popover, you should be able to pull it off. Set the progress bar viewport to be inside the popover, and then in the `keyup` event you can show the popover.
