### ISSUE TITLE
Is there anyway we can position the 'verdict and error messages' 

### ISSUE THREAD

**Issue by thusithak** [ablanco/jquery.pwstrength.bootstrap#68]
when using the popover, is there a way to use bootstrap popover's placement properties?

**Comment by ablanco** [comment]
I'm afraid not. It's hardcoded: https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/ui.js#L106

That should be an option. I'll leave this issue open to remind me of it.

**Comment by thusithak** [comment]
Great!
Thanks for the prompt response..!

**Comment by ablanco** [comment]
I've added the option in 0b80bb0c6f4b5ec7ad8c9fa23a072e528d40e5b0

It will be available in the next release.
