### ISSUE TITLE
Verdict in differents colors

### ISSUE THREAD

**Issue by Marinc** [ablanco/jquery.pwstrength.bootstrap#71]
Hi ! 
I try to put some HTML in the verdicts ( like : '<span class="weak">Weak</span>' ) but it doesn't work. (do i use the correct method ?) Is it possible to have some colours on the verdicts ? 
Thank you so much ! 
Have a nice day !

**Comment by ablanco** [comment]
Hi Marinc. It is possible to have html in the verdicts. You just have to overwrite the verdicts in the proper option and write there your html. There is an example of this here: https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap3/htmlVerdicts.html
