### ISSUE TITLE
Rules for easy password or RegEx

### ISSUE THREAD

**Issue by mantia11** [ablanco/jquery.pwstrength.bootstrap#73]
Hia!

Sorry, this is not issue, but I'm working now with this great plugin (thnx a lot for it) and I need to make "qwerty1" or "1aaaaaa" passwords accepted. Could you please help me to tell where I can read what rule option what means or just help me to set rules for such easy password or tell how to set regex in options if this possible?

Thanks a million for your attention to this message! =) :-D

**Comment by ablanco** [comment]
Hi mantia11,
you can activate or deactivate validation rules in the options. Disabling rules like `wordSequences` or `wordRepetitions` will help you to make the those passwords valid. You can also change the scores for each rule so the result is more to your liking. Giving lower scores to the rules that penalize your password will also help you.

You can find the list of rule-related options [here](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md#rules).

Another strategy is to lower the required password score to change from one verdict to another. You'll find the proper option `scores` at the end of the [UI options section](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md#user-interface).

Last but not least, you can also create your own rules encouraging or penalizing the passwords as you want. You can find how to do it [here](https://github.com/ablanco/jquery.pwstrength.bootstrap#adding-custom-rules) and an example [here](https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap2/rules.html).
