### ISSUE TITLE
Errors for Custom Rules

### ISSUE THREAD

**Issue by jthomp** [ablanco/jquery.pwstrength.bootstrap#78]
Hello,

In my implementation, I want to ban certain words from being used as passwords and weight them differently in terms of score.

For example, a word like "foobarbaz" would get a -100.

Below is how I've implemented my custom rule, based on an example I found.

```
var banned = ['foobarbaz', bazbarfoo', 'barfoobaz'];

// ... other implementation code.

$element.pwstrength("addRule", "bannedRule", function (options, word, score) {
   var result = false;
   $.each(banned, function (i, item) {
    var re = new RegExp(item, "gi");
    if (word.match(re)) {
      result = score;
     }
   });
   return result;
}, -100, true);
```

My question is, how do I define an error message for this rule? Something like "You cannot use that password," etc.

Thanks!

**Comment by ablanco** [comment]
Hi Justin,
you just need to define the error message related to your rule in the `errorMessages` options. That option is a dictionary where the name of the rule is the key and the value is the error message. Then, whenever your rule returns a negative value, the message is gonna show up.

For example:

```javascript
var banned = ['foobarbaz', 'bazbarfoo', 'barfoobaz'];

// ... other implementation code.

var options = { ui: { 
  errorMessages: {
    wordLength: "Your password is too short",
    wordNotEmail: "Do not use your email as your password",
    wordSimilarToUsername: "Your password cannot contain your username",
    wordTwoCharacterClasses: "Use different character classes",
    wordRepetitions: "Too many repetitions",
    wordSequences: "Your password contains sequences",
    bannedRule: "Your password includes a banned word"
  },
  showErrors: true
}};
var $element = $(':password').pwstrength(options);

$element.pwstrength("addRule", "bannedRule", function (options, word, score) {
   var result = 0;
   $.each(banned, function (i, item) {
    var re = new RegExp(item, "gi");
    if (word.match(re)) {
      result = score;
     }
   });
   return result;
}, -100, true);
```

Be aware that I changed the default value of the rule to 0. With ```false```, because of javascript automatic casting, it always rendered the error message.

**Comment by jthomp** [comment]
That worked perfectly. Many thanks!
