### ISSUE TITLE
How to prevent a submit if minimum required score was not achieved 

### ISSUE THREAD

**Issue by fernandomoitinho** [ablanco/jquery.pwstrength.bootstrap#79]
First of all, great job putting this together.

I cannot find a way to prevent on client side to get the score for all the pwstrength instances, and then prevent a form submit if a predefined score was not achieved. Do you have any idea were i can get the score of each pwstrength instance?

Thanks

**Comment by ablanco** [comment]
Hi Fernando,
there is no method to get the score from the instances. The score is not stored, is calculated every time the password changes.

But you can add a callback on the [update event (onKeyUp)](https://github.com/ablanco/jquery.pwstrength.bootstrap#callback-functions) and there you'll have access to the current score. Then you can use that score for enabling or disabling the submit button or whatever you need.

**Comment by fernandomoitinho** [comment]
Sounds great, I will try that approach. 

Thanks a lot 

Regards,
Fernando Moitinho

**Comment by raisonon** [comment]
Not sure etiquette on posting on old issues. Hope not a problem, but this is what I used. Not ideal as I wanted to integrate better with jQuery validate, but does the trick:

         `            onKeyUp: function (evt, data) {
                //$("span.pwd-messages").text("Current length: " + $(evt.target).val().length + " and score: " + data.score);
                if (data.score > 35) {
                    $("span.pwd-messages").text("");
                    $('#ajaxregister button[name=submit]').prop("disabled",false);
                } else {
                    $("span.pwd-messages").text("Password not strong enough");
                    $('#ajaxregister button[name=submit]').prop("disabled",true);
                }`
