### ISSUE TITLE
Show verdicts + score

### ISSUE THREAD

**Issue by punchi** [ablanco/jquery.pwstrength.bootstrap#80]
I would be nice to have an option to show the score next to the verdicts, as I have a "the password must have an score of X or more" it's more clean to show the score on the same bar.

I didn't see the option, just by doing some tricks... an incorporated option would be great =)

Thanks for this plugin! :D

**Comment by ablanco** [comment]
Implemented in b516e08596de1e8a53d87021646f0e0bab4995a7
It will be available in the next release
