### ISSUE TITLE
Bootstrap 4 and container

### ISSUE THREAD

**Issue by iWader** [ablanco/jquery.pwstrength.bootstrap#83]
Using bootstrap 4 and setting a contain seems to stop everything from working leaving just an empty progress bar.

```javascript
        $('#password').pwstrength({
            common: {
                debug: true
            },
            ui: {
                bootstrap4: true,
                container: "#password-strength"
            }
        });
```

I've attached to the password field in the screenshot and the black border is my container, however it doesn't seem to use the container. Unsure if this is effected by bootstrap 4 but I'd assume it is.

<img width="1081" alt="screenshot 2016-02-12 16 27 11" src="https://cloud.githubusercontent.com/assets/2007548/13013054/b07f3f64-d1a5-11e5-91b7-3328e0fa7414.png">

**Comment by ablanco** [comment]
Hi Wade,
the password field must be inside of the container for it to work. If you what you want is to show the progress bar in the black bordered section, what you need to do is to use the viewport option and set the container to a common parent of the input and the viewport.
