### ISSUE TITLE
Overriding spanError issue

### ISSUE THREAD

**Issue by RobMaskell** [ablanco/jquery.pwstrength.bootstrap#84]
Tried using the suggested override for spanError from the docs, I had an error and also an "undefined" error for each possible error message. This fixes it and could become the suggested override for the docs, unless you can improve it.

```
function (options, key) {
   var text = options.ui.errorMessages[key];
   return (typeof text != 'undefined')?'<span style="color: #d52929">' + text + '</span>':'';
}
```

I'd also like the option to provide an id of an element to be replaced with the output of this function rather than being wrapped by an ul/li, so I can position the error specifically for the field to match other errors on the form. Unless there is a way to position the error somewhere other than under the control?

Great work though :)

**Comment by ablanco** [comment]
Hi Rob,
you're right, the example in the docs is not controlling the possibility of an undefined value, while the default version of that function in the code does it. I'll fix the docs.

It's possible to control where the errors show up with the `viewports` option. The viewports are meant to be contained by the container, if the `container` option is not defined, it defaults to the parent of the password input, so you might want to define it.

**Comment by RobMaskell** [comment]
Ok I'll see if I can use the viewports / container to make it do what I want, thanks

**Comment by RobMaskell** [comment]
Ok I can get the error to appear where I want it, using the viewports as you suggested, is there a way to not have the html fragment returned by my custom function wrapped in an unordered list?

**Comment by ablanco** [comment]
No, sorry, that's hardcoded. It's always a ul with li inside.
