### ISSUE TITLE
Show verdict in selected viewport and errors in popover

### ISSUE THREAD

**Issue by piotrm50** [ablanco/jquery.pwstrength.bootstrap#85]
I would like to display verdict in selected viewport and errors in popover, so that popover is only displayed when errors occur.

**Comment by ablanco** [comment]
Hi Piotr, I'm afraid the library is not that flexible. You could select not to show the verdict and then manually with the onKeyUp function show them where you want. Or mark them to be shown in the progressbar, then they won't show up in the popover.
