### ISSUE TITLE
Do NOT remove error message after criteria has been met

### ISSUE THREAD

**Issue by dexterca** [ablanco/jquery.pwstrength.bootstrap#87]
Is there a way to **NOT** remove error message after it's criteria has been met? In other words, I want to change classes of each error message after it's criteria has been met (not remove it from the DOM).

![mail-chimp-pwsd-criteria](https://cloud.githubusercontent.com/assets/485903/13851292/f8a3aa52-ec33-11e5-8e31-d9dcbf1ef2ac.gif)

**Comment by ablanco** [comment]
Hi Casey,
I'm afraid is not possible to have the behavior you're asking about. It would require some serious refactor of the code.
