### ISSUE TITLE
Incorrect rendering of progressbar when password value is erased

### ISSUE THREAD

**Issue by interDist** [ablanco/jquery.pwstrength.bootstrap#89]
The UI is not consistent: When the password field is empty at start, the progress bar is empty too. However, after typing a value and completely erasing it, the progress bar will remain at 1% instead of ‘emptying’ (due to a fix for score == 0). This is slightly puzzling for the end user.

I suggest to set the score to `undefined` instead of zero, in [methods.js:L31](/ablanco/jquery.pwstrength.bootstrap/blob/35115e436fe0aa1a056c1f484d4c72fbfc767632/src/methods.js#L31), since `0` does have semantic value and the strength score of the password can be zero or even negative. This will require changes:
* in `ui.getVerdictAndCssClass` (probably the check for `undefined` can be combined with the first case), 
* in `ui.updateUI` at [ui.js:L275](/ablanco/jquery.pwstrength.bootstrap/blob/35115e436fe0aa1a056c1f484d4c72fbfc767632/src/ui.js#L275) by checking for `undefined` instead of `0`, 
* and in `ui.percentage` – check for `undefined` prior to calculation, or even without the need to modify `ui.percentage` :
```javascript
barPercentage = score === undefined ? 0 : ui.percentage(score, options.ui.scores[3]);
```

**Comment by ablanco** [comment]
Implemented in 6ca4181cea7afd897bf044fb597549168b4ade6b, it will be available in the next release.

I have finally chosen to leave the minimum value of the progressbar as an option, so each developer can choose what they think is best. Now the behavior is consistent, and it initializes to same minimum than when the password is deleted.

I've left the default value at 1%. It looks like it's waiting for the user to type something in, which I like.
