### ISSUE TITLE
Allow custom CSS classes to be specified

### ISSUE THREAD

**Issue by interDist** [ablanco/jquery.pwstrength.bootstrap#90]
Currently we have the ability to customize the generated widget only by defining additional rules for the CSS classes `progress-bar`, `password-verdict`, etc. It would be great if custom classes could be specified for each of the generated components of the widget, such that they are added automatically to the HTML elements.

**Comment by ablanco** [comment]
@interDist, you can make use of the `viewports` option to put the progressbar inside a container with your own class, and use that as a starting point for custom css rules to style the bar. Wouldn't that be better than having more options to deal with?

**Comment by interDist** [comment]
My proposition actually relates to each of the created objects, not just the progress bar. This would allow reusage of already existant CSS classes, in order to style everything consistently with the rest of the web page. In some cases, a container will not work, for example if I want to apply additional bootstrap styles to the created objects.

**Comment by ablanco** [comment]
In that case you can apply the same CSS rules to different selectors, the container and your own classes. I think the container option is enough to identify the strength meter and style it. I don't want to add many more configuration options, the plugin has plenty of options as it is.

Can you put an example (in actual html) where it wouldn't work?

**Comment by interDist** [comment]
The most quick example I can think of is (re)usage of `progress-bar-striped` (and `active`), from the Bootstrap 3 CSS. 
But I do understand your point and if not much interest is shown by other users of the plugin, I'm not going to insist :)

**Comment by ablanco** [comment]
I see, now I get it. I didn't realize what you meant before.

Ok, that makes sense. I'll put something together.

**Comment by ablanco** [comment]
Implemented in e40d5fcf669c2df8157917d440ca70aad75ea4bd

It will be available in the next release.
