### ISSUE TITLE
The widget doesn't play nice with the "min-width" attribute of progress-bar

### ISSUE THREAD

**Issue by interDist** [ablanco/jquery.pwstrength.bootstrap#91]
Bootstrap’s `progress-bar` allows setting a `min-width` attribute so that a small chunk is rendered even when the value is 0. But when setting this attribute, the progress bar within the widget will have an incorrect color (the default blue one), because the color class is not applied yet.

The widget could be modified to set the `progress-bar-danger` class by default (taking into consideration Bootstrap’s version and color customizations), yet I think a better solution would be to support a _minProgressBarWidth_ ui option, that – when set – will add the `min-width` attribute to the progress bar `<div>` if password value is present, and remove the `min-width` attribute otherwise (such that no progress bar is drawn when the password field is empty).

The `min-width` is very handy for ensuring the first verdict is visible always, even if the score is small. For me, the exact score is less important and much bigger need is for the users to see the verdict (instead of just a few letters of a clipped word).

**Comment by ablanco** [comment]
This renders 6ca4181cea7afd897bf044fb597549168b4ade6b a bit useless, I should have read this issue before doing that >_<

I'm gonna read about the min width option and see how it behaves between bootstrap 2, 3 and 4. Maybe I can change the previous commit's code to make use of that property.

**Comment by ablanco** [comment]
In bootstrap 2 and 3 it would be possible to use the `min-width` property. In bootstrap 4 not. They've changed it for the native html 5 progress element, it has a `max` and a `value`, but not a `min`.

My laziness is getting the best of me, and I don't think is worth it to make it use the `min-width` property. 6ca4181cea7afd897bf044fb597549168b4ade6b already handles this, even if it's just by making sure the calculated percentage never goes under a minimum value.

@interDist thoughts?

**Comment by interDist** [comment]
I think there should be two different minima: one is the minimum score, that is the progress bar is capped (from the bottom) at this value, allowing to make sure that the lowest verdict is always visible (for example, I would set it at 15%). The other one is the minimum progress bar shown, for a situation when the value is erased (for example, this one I would set at 0%, someone else might prefer 1%, as you said, it looks like waiting for input).

**Comment by ablanco** [comment]
So if I'm understanding correctly your proposal is that the plugin should have two minimums. One for when the input is empty, and another for the lowest possible score of the password. So if you set the first one to 0%, and the second to 15%, then the bar would show up empty and after the user inputs just one char it would jump to 15% and start growing from there. Is that correct?

It would only be possible to achieve that using the `min-width` property if the bar DOM node is not there for the empty situation. But that would mean that it wouldn't be possible to have something different than a 0% for an empty field. I don't like that, so I'm discarding the `min-width` option.

It would be possible to have that behavior just by having two different options available. One for each case. But then the plugin would have to differentiate when the input is empty from when is just a terrible password. Which returns us back to supporting `undefined` as a possible score.

Well, it shouldn't be hard. I just need to adapt the `updateUI` function :)

**Comment by ablanco** [comment]
Implemented in 54a2240bb8050b956fedea86e5cca90c6c72417f

It will be available in the next release.

**Comment by interDist** [comment]
Revisiting this issue. The percentages work nice as long as your form-factor is predefined. If you need to support varying form-factors (read: mobile- and desktop-flexible layout), the percentages do not work anymore: for small screens (e.g., 320px, 360px) the initial progress chunk is too small and the initial verdict is clipped, confusing the users; for large screens the initial progress chunk is way too large (in my case, I need to set the min percentageto 25% for it to work on the small screens!)... 😕

**Comment by interDist** [comment]
@ablanco I think a new setting `progressBarMinWidth` will solve the issue. If provided, it will set the `min-width` CSS property on the progress bar. It can be combined with the existing `progressBarMinPercentage` setting because the `min-width` property takes precedence over the `width` property (in this case, provided as a percentage).

**Comment by ablanco** [comment]
Fixed in release 3.0.3

**Comment by interDist** [comment]
I hate to be a jerk... I finally have gotten to updating the package, and was rejoicing in anticipation of correcting the form-factor presentation issues. But then I discovered that there is a collision with `progressBarEmptyPercentage` 😔 

Specifically, in our case, `progressBarEmptyPercentage` is set to 0 (so no progress bar is displayed when no input was provided); and the `progressBarMinWidth` should play a role only when there is some input, similarly to `progressBarMinPercentage`. That was actually my intent in the original comment (https://github.com/ablanco/jquery.pwstrength.bootstrap/issues/91#issuecomment-458465300)...

**Comment by ablanco** [comment]
Fixed in release 3.0.4 :)
