### ISSUE TITLE
verdictLevel is undefined

### ISSUE THREAD

**Issue by troosan** [ablanco/jquery.pwstrength.bootstrap#93]
verdictText is set but verdictLevel is not.

The problem is in methods.js at line 47, it should be
`verdictLevel = verdictText[1];`
instead of
`verdictLevel = verdictText[2];`

**Comment by ablanco** [comment]
Thanks for spotting the error. It's fixed in 8ad120a1e421b4d8ea84723a6b9db057d2c03bc3 and will be available in the next release.
