### ISSUE TITLE
How to down score certain words?

### ISSUE THREAD

**Issue by nickwuk** [ablanco/jquery.pwstrength.bootstrap#94]
I've configured pwstrength with the following rules which I believe are in fact default settings:

`			rules: {
				activated: {
					wordNotEmail: true,
					wordRepetitions: true,
					wordUpperLowerCombo: true,
					wordLetterNumberCombo: true
				},
			},`

If I enter 'password' for my password the strength shows as 'Normal', how can I either disallow certain common words and down score when not alphanumeric, so that I can disable the submit button when the verdict is 'Weak' or 'Very Weak'?

**Comment by ablanco** [comment]
Hi nickwuk,
you can add [custom rules](https://github.com/ablanco/jquery.pwstrength.bootstrap#adding-custom-rules) and use it to penalize the forbidden words. You can see an example [here](https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/bootstrap2/rules.html).

There is an option named [`onKeyUp`](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md) that will allow you to set up a callback where you can use the score to enable/disable a button.
