### ISSUE TITLE
Password strength meter updated only on blur on iOS 9 Safari

### ISSUE THREAD

**Issue by juliemoynat** [ablanco/jquery.pwstrength.bootstrap#95]
Hello,
I noticed, on iOS 9 and Safari, that the password strength meter is updated only when we put the focus out of the password field.
It's OK on iOS 7 and 8.
Can you fix it?

**Comment by ablanco** [comment]
Hi Julie,
I don't own an iphone so I cannot try this.

Events are added in [this point](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/methods.js#L94). Could you try to add the `keypress` event and see if it works fine in ios9? Maybe the keyup event doesn't fire in that ios version.

**Comment by juliemoynat** [comment]
I'm not really a developer so... that's complicated for me to test that... Could you be more precise about what I can do to see if it works fine?

**Comment by ablanco** [comment]
I've made the change in this file: http://pastebin.com/0Rn91QF9

Could you try with that copy of the plugin?

**Comment by juliemoynat** [comment]
It works!

**Comment by ablanco** [comment]
[Apparently ios 9 has problems with the `keyup` event](http://stackoverflow.com/questions/33152960/ios-9-keyup-event-not-firing). Keyup should work fine, I guess apple screw it up. All I can do is to add a new option with a list of events for the plugin to listen to, with `keyup` on it by default. That way you can customize the events when the client is an ios 9.

**Comment by juliemoynat** [comment]
Unfortunately, that's a quite old problem now...
Would your fix be easy to use? I can't imagine.
And if it works on iOS 9, would it still work with all other browser?

**Comment by ablanco** [comment]
Yes, it would be easy to use. Whoever uses the plugin can change the initialization options depending of the clients' browsers, using modernizr or something similar. And if it's properly used by whoever is coding the page, then yes, it would work in all browsers.

**Comment by juliemoynat** [comment]
Okay. Anyway, I can't see another solution.

**Comment by ablanco** [comment]
Fixed in df7c212ac53f2c8756aed4505dd9dd261c6d82cd

It will be available in the next release.
