### ISSUE TITLE
Cannot find module 'jsdom'

### ISSUE THREAD

**Issue by danimalweb** [ablanco/jquery.pwstrength.bootstrap#96]
I'm using this in my project which uses Babelify.

I've run `npm install pwstrength-bootstrap`

add added: 
`import 'pwstrength-bootstrap/dist/pwstrength-bootstrap.js';` to my JS file.

When I compile it finds the file ok, but I get an error: 

`[Error: Cannot find module 'jsdom' from '/[REMOVED]/node_modules/pwstrength-bootstrap/dist']`

I'm importing other jQuery plugins that are working fine and at the top of my file I have `
var $ = window.jQuery;` so I know $ is bound to my external jQuery file.

Any ideas?

Running `npm install jsdom` did fix my issue, but is jsdom a dependency of this plugin

Thanks.

**Comment by ablanco** [comment]
Hi Daniel,
jsdom is only used in the tests. I've never used `import` with the plugin. Is that the server side? Or is in the client side?

**Comment by danimalweb** [comment]
It's client side via a transpiler (Babel) to make it compatible.
https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import

Looks like this lib is not compatible using import. I just checked by JS file and it has included by jQuery and JSDom making my total compiled JS file almost 5MB.

It would need to be updated to use something like UMD (Universal Module Definition) https://github.com/umdjs/umd

This is a great jQuery plugin, I might have a look at forking it and making it compatible if I find some time.

**Comment by ablanco** [comment]
Yes, it's not UMD compatible. But if you want to make it compatible I'll more than happy to include. Contributions are welcome :smile:
