### ISSUE TITLE
Compatibility issue with jquery-placeholder in IE9

### ISSUE THREAD

**Issue by nickwuk** [ablanco/jquery.pwstrength.bootstrap#98]
It seems that pwstrength works in conjuction with [jquery-placeholder](https://github.com/mathiasbynens/jquery-placeholder) in the latest popular browsers but in IE9 the meter bar shows but does not function and no messages when installed with jquery-placeholder.

**Comment by ablanco** [comment]
Sorry Nick, I'm afraid I don't care much for IE users, and even less for IE9 or older. I don't know why both plugins don't work at the same time in that specific browser. The truth is this is the first time I've heard about that placeholder plugin. It looks like it gives support for that to older browsers, a nice pollyfill, but unnecessary in 2016, IMHO.

I'm afraid the only solution I have for you is to tell your users to upgrade to Edge or to switch to a less crappy browser.
